In [19]:
step_data = np.array([
    [1, 6012],
    [2, 7012],
    [3, 6886],
    [4, 7250],
    [5, 4598],
    [6, 5564],
    [7, 6971],
    [8, 7769],
    [9, 8032],
    [10, 9569]
])
step_data[ :0]



array([], shape=(0, 2), dtype=int64)

In [6]:
import numpy as np

array([], shape=(0, 2), dtype=int64)

In [21]:
step_data = np.array([
    [1, 6012],
    [2, 7012],
    [3, 6886],
    [4, 7250],
    [5, 4598],
    [6, 5564],
    [7, 6971],
    [8, 7769],
    [9, 8032],
    [10, 9569]
])
step_data[ :0]



array([], shape=(0, 2), dtype=int64)

In [22]:
print(step_data)

[[   1 6012]
 [   2 7012]
 [   3 6886]
 [   4 7250]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7769]
 [   9 8032]
 [  10 9569]]


In [23]:
step_data[:,0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
step_data[:,1]

array([6012, 7012, 6886, 7250, 4598, 5564, 6971, 7769, 8032, 9569])

In [25]:
step_data[:,1]+=2000

In [27]:
max_stp=np.max(step_data)

In [28]:
print(max_stp)

11569


In [31]:
step_data[step_data[:,1]>7000]

array([[    1,  8012],
       [    2,  9012],
       [    3,  8886],
       [    4,  9250],
       [    6,  7564],
       [    7,  8971],
       [    8,  9769],
       [    9, 10032],
       [   10, 11569]])

In [32]:
sorted_step=np.sort(step_data[:1])
sorted_step

array([[   1, 8012]])

In [33]:
sorted_step=np.sort(step_data[:9])
sorted_step

array([[    1,  8012],
       [    2,  9012],
       [    3,  8886],
       [    4,  9250],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9769],
       [    9, 10032]])