In [35]:
import numpy as np


In [37]:
step_data = np.array([
    [1, 4335],
    [2, 9552],
    [3, 7332],
    [4, 4504],
    [5, 5335],
    [6, 7552],
    [7, 8332],
    [8, 6504],
    [9, 8965],
    [10, 7689]
])


In [38]:
print(step_data)

[[   1 4335]
 [   2 9552]
 [   3 7332]
 [   4 4504]
 [   5 5335]
 [   6 7552]
 [   7 8332]
 [   8 6504]
 [   9 8965]
 [  10 7689]]


In [39]:
step_data[:,1]+=1000

In [40]:
step_data[:,1]>7000

array([False,  True,  True, False, False,  True,  True,  True,  True,
        True])

In [41]:
np.sort(step_data[:,1])

array([ 5335,  5504,  6335,  7504,  8332,  8552,  8689,  9332,  9965,
       10552])